FORMAT: 1A

# Cerberus Rails API

This project was born to validate access to a product features by users saved on a system.

# Group Clients

## Clients Collection [/clients]

### List all clients [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Client])

### Create a client [POST]
+ Request (application/json)
    + Attributes
        + name: `Client name` (string, required) - Client name

+ Response 201 (application/json)
    + Attributes (Client)

## Client Resource [/clients/{id}]

### Show a client [GET /clients/{id}{?show_products}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Client id
    + show_products: `true` (string, optional) - Show products indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    
+ Response 200 (application/json)
    + Attributes (ClientShowProducts)

### Update a client [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Client id
+ Attributes
    + name: `Client name` (string, required) - Client name

+ Response 200 (application/json)
    + Attributes (Client)

# Group Products

## Products Collection [/products]

### List all products [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Product])

### Create a product [POST]
+ Request (application/json)
    + Attributes
        + name: `Product name` (string, required) - Product name
        + description: `Product description` (string, required) - Product description

+ Response 201 (application/json)
    + Attributes (Client)

## Product Resource [/products/{id}]

### Show a product [GET /products/{id}{?show_clients}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Product id
    + show_clients: `true` (string, optional) - Show clients indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    
+ Response 200 (application/json)
    + Attributes (ProductShowClients)

### Update a product [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Product id
+ Attributes
    + name: `Product name` (string, required) - Product name
    + description: `Product description` (string, required) - Product description

+ Response 200 (application/json)
    + Attributes (Product)

## Data Structures

### Client (object)
+ id: `1` (number, required)
+ name: `Client name` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### ClientShowProducts (object)
+ id: `1` (number, required)
+ name: `Client name` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ products: (array[Product], optional)

### Product (object)
+ id: `1` (number, required)
+ name: `Product name` (string, required)
+ description: `Product description` (string, optional)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### ProductShowClients (object)
+ id: `1` (number, required)
+ name: `Product name` (string, required)
+ description: `Product description` (string, optional)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ clients: (array[Client], optional)
