FORMAT: 1A

# Cerberus Rails API

This project was born to validate access to a product features by users saved on a system.

# Group Clients

## Clients Collection [/clients]

### List all clients [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Client])

### Create a client [POST]
+ Request (application/json)
    + Attributes
        + name: `Client name` (string, required) - Client name

+ Response 201 (application/json)
    + Attributes (Client)

## Client Resource [/clients/{id}]

### Show a client [GET /clients/{id}{?show_products}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Client id
    + show_products: `true` (string, optional) - Show products indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    
+ Response 200 (application/json)
    + Attributes (ClientShowProducts)

### Update a client [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Client id
+ Attributes
    + name: `Client name` (string, required) - Client name

+ Response 200 (application/json)
    + Attributes (Client)

# Group Products

## Products Collection [/products]

### List all products [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Product])

### Create a product [POST]
+ Request (application/json)
    + Attributes
        + name: `Product name` (string, required) - Product name
        + description: `Product description` (string, required) - Product description

+ Response 201 (application/json)
    + Attributes (Client)

## Product Resource [/products/{id}]

### Show a product [GET /products/{id}{?show_clients,show_features}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Product id
    + show_clients: `true` (string, optional) - Show clients indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    + show_features: `true` (string, optional) - Show features indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    
+ Response 200 (application/json)
    + Attributes (ProductShowClientsAndFeatures)

### Update a product [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Product id
+ Attributes
    + name: `Product name` (string, required) - Product name
    + description: `Product description` (string, required) - Product description

+ Response 200 (application/json)
    + Attributes (Product)

# Group Users

## Users Collection [/users]

### List all users [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[User])

### Create a user [POST]
+ Request (application/json)
    + Attributes
        + name: `User name` (string, required) - User name
        + login: `login` (string, required) - Login

+ Response 201 (application/json)
    + Attributes (User)

## User Resource [/users/{id}]

### Show a user [GET /users/{id}{?show_details}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - User id
    + show_details: `true` (string, optional) - Show user details
        + Default: `false`
        + Members
            + `true`
            + `false`
    
+ Response 200 (application/json)
    + Attributes (UserShowDetails)

### Delete a user [DELETE /users/{id}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - User id
    
+ Response 204 (application/json)

### Update a user [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - User id
+ Attributes
    + name: `User name` (string, required) - User name
    + login: `login` (string, required) - Login

+ Response 200 (application/json)
    + Attributes (User)

# Group Users-Roles

## User-Role Resource [/users/{user_id}/roles/{role_id}]

### Create user-role association [POST]
+ Request (application/json)
+ Parameters
    + user_id: `1` (number, required) - User id
    + role_id: `2` (number, required) - Role id

+ Response 201 (application/json)
    + Attributes (UserRole)

### Delete user-role association [DELETE]
+ Request (application/json)
+ Parameters
    + user_id: `1` (number, required) - User id
    + role_id: `2` (number, required) - Role id

+ Response 204 (application/json)

# Group Contracts

## Contracts Collection [/contracts{?show_product_details,show_client_details}]

### List all contracts [GET]
+ Request (application/json)
+ Parameters
    + show_product_details: `true` (string, optional) - Show product details indicator
        + Default: `false`
        + Members
            + `true`
            + `false`
    + show_client_details: `true` (string, optional) - Show client details indicator
        + Default: `false`
        + Members
            + `true`
            + `false`

+ Response 200 (application/json)
    + Attributes (array[ContractsShowClientAndProduct])

### Create a contract [POST]
+ Request (application/json)
    + Attributes
        + client_id: `123` (number, required) - Client id
        + product_id: `456` (number, required) - Product id
        + enabled: `true` (boolean, optional) - Enabled indicator
            + Default: `false`

+ Response 201 (application/json)
    + Attributes (Contract)

# Group Features

## Features Collection [/features]

### List all features [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Feature])

### Create a feature [POST]
+ Request (application/json)
    + Attributes
        + name: `Feature name` (string, required) - Feature name
        + product_id: `123` (number, required) - Product id
        + enabled:  `true` (boolean, optional) - Enabled indicator
            + Default: `false`
        + read_only:  `true` (boolean, optional) - Read only indicator
            + Default: `false`

+ Response 201 (application/json)
    + Attributes (Feature)

## Feature Resource [/features/{id}]

### Show a feature [GET /features/{id}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Feature id

+ Response 200 (application/json)
    + Attributes (Feature)

### Delete a feature [DELETE /features/{id}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Feature id
    
+ Response 204 (application/json)

### Update a feature [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Feature id
+ Attributes
    + name: `Feature name` (string, required) - Feature name
    + product_id: `123` (number, required) - Product id
    + enabled:  `true` (boolean, optional) - Enabled indicator
        + Default: `false`
    + read_only:  `true` (boolean, optional) - Read only indicator
        + Default: `false`

+ Response 200 (application/json)
    + Attributes (Feature)

# Group Features-Roles

## Feature-Role Resource [/features/{feature_id}/roles/{role_id}]

### Create feature-role association [POST]
+ Request (application/json)
+ Parameters
    + feature_id: `1` (number, required) - Feature id
    + role_id: `2` (number, required) - Role id

+ Response 201 (application/json)
    + Attributes (FeatureRole)

### Delete feature-role association [DELETE]
+ Request (application/json)
+ Parameters
    + feature_id: `1` (number, required) - Feature id
    + role_id: `2` (number, required) - Role id

+ Response 204 (application/json)

# Group Roles

## Roles Collection [/roles]

### List all roles [GET]
+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (array[Role])

### Create a role [POST]
+ Request (application/json)
    + Attributes
        + name: `Role name` (string, required) - Role name
        + contract_id: `123` (number, required) - Contract id
        + enabled:  `true` (boolean, optional) - Enabled indicator
            + Default: `false`

+ Response 201 (application/json)
    + Attributes (Role)

## Role Resource [/roles/{id}]

### Show a role [GET /roles/{id}{?show_users}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Role id
    + show_users: `true` (string, optional) - Show users indicator
        + Default: `false`
        + Members
            + `true`
            + `false`

+ Response 200 (application/json)
    + Attributes (RoleShowUsers)

### Delete a Role [DELETE /roles/{id}]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Role id
    
+ Response 204 (application/json)

### Update a feature [PUT]
+ Request (application/json)
+ Parameters
    + id: `1` (number, required) - Role id
+ Attributes
    + name: `Role name` (string, required) - Role name
    + contract_id: `123` (number, required) - Contract id
    + enabled:  `true` (boolean, required) - Enabled indicator
        + Default: `false`

+ Response 200 (application/json)
    + Attributes (Role)

## Data Structures

### Client (object)
+ id: `1` (number, required)
+ name: `Client name` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### ClientShowProducts (object)
+ id: `1` (number, required)
+ name: `Client name` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ products: (array[Product], optional)

### Product (object)
+ id: `1` (number, required)
+ name: `Product name` (string, required)
+ description: `Product description` (string, optional)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### User (object)
+ id: `1` (number, required)
+ name: `User name` (string, required)
+ login: `login` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### UserShowDetails (object)
+ id: `1` (number, required)
+ name: `User name` (string, required)
+ login: `login` (string, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ roles: (array[RolesUserDetails], optional)

### RolesUserDetails (object)
+ id: `1` (number, required)
+ name: `Role name` (string, required)
+ client: (ClientUserDetails, required)
+ product: (ProductUserDetails, required)

### ProductUserDetails (object)
+ id: `1` (number, required)
+ name: `Product name` (string, required)
+ features: (array[FeaturesUserDetails], optional)

### FeaturesUserDetails (object)
+ id: `3` (number, required)
+ name: `Feature name` (string, required)

### ClientUserDetails (object)
+ id: `1` (number, required)
+ name: `Client name` (string, required)

### Feature (object)
+ id: `3` (number, required)
+ product_id: `1` (number, required)
+ name: `Feature name` (string, required)
+ enabled: `true` (boolean, required)
+ read_only: `false` (boolean, required)
+ created_at: `2020-10-12T22:10:56.811Z` (string, required)
+ updated_at: `2020-10-12T22:10:56.811Z` (string, required)

### UserRole (object)
+ id: `3` (number, required)
+ user_id: `1` (number, required)
+ role_id: `1` (number, required)
+ created_at: `2020-10-12T22:10:56.811Z` (string, required)
+ updated_at: `2020-10-12T22:10:56.811Z` (string, required)

### FeatureRole (object)
+ id: `3` (number, required)
+ feature_id: `1` (number, required)
+ role_id: `1` (number, required)
+ created_at: `2020-10-12T22:10:56.811Z` (string, required)
+ updated_at: `2020-10-12T22:10:56.811Z` (string, required)

### Contract (object)
+ id: `1` (number, required)
+ client_id: `456` (number, required)
+ product_id: `123` (number, required)
+ enabled: `true` (boolean, required)
+ created_at: `2020-10-12T22:10:56.811Z` (string, required)
+ updated_at: `2020-10-12T22:10:56.811Z` (string, required)

### ContractsShowClientAndProduct (object)
+ id: `1` (number, required)
+ client_id: `456` (number, required)
+ product_id: `123` (number, required)
+ enabled: `true` (boolean, required)
+ created_at: `2020-10-12T22:10:56.811Z` (string, required)
+ updated_at: `2020-10-12T22:10:56.811Z` (string, required)
+ product: (Product, optional)
+ client: (Client, optional)

### ProductShowClientsAndFeatures (object)
+ id: `1` (number, required)
+ name: `Product name` (string, required)
+ description: `Product description` (string, optional)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ clients: (array[Client], optional)
+ features: (array[Feature], optional)

### Role (object)
+ id: `1` (number, required)
+ contract_id: `123` (number, required)
+ name: `Role name` (string, required)
+ enabled: `true` (boolean, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)

### RoleShowUsers (object)
+ id: `1` (number, required)
+ contract_id: `123` (number, required)
+ name: `Role name` (string, required)
+ enabled: `true` (boolean, required)
+ created_at: `2020-10-12T14:32:34.290Z` (string, required)
+ updated_at: `2020-10-12T14:32:34.290Z` (string, required)
+ users: (array[User], optional)
