FROM ruby:2.7.2-alpine
WORKDIR /usr/src/app
RUN apk --no-cache add build-base tzdata postgresql-dev
ENV RUBYOPT="-W:no-deprecated"
ENV RAILS_LOG_TO_STDOUT="on"
COPY Gemfile Gemfile.lock ./
RUN gem update --system \
    && gem install bundler -v 2.0.2 \
    && gem install rails -v 6.1.2.1 \
    && bundle install
COPY ./app ./app
COPY ./bin ./bin
COPY ./config ./config
COPY ./db/migrate ./db/migrate
COPY ./lib ./lib
COPY ./log ./log
COPY config.ru LICENSE.md Rakefile ./
